version: "3.3"

services:

  mongo:
    image: "mongo:3.2"
    ports:
      - "27017:27017"
    networks:
      - "backend"
    restart: always
    volumes:
      - "db-data:/data/db"

  mongoExpress:
    image: "mongo-express:0.42.2"
    ports:
      - "8081:8081"
    networks:
      - "backend"
    links:
      - "mongo"
    restart: always

  quartermaster:
    image: "reflectoring/quartermaster:latest"
    restart: always
    ports:
      - "8080:8080"
      - "8090:8090"
    networks:
      - "backend"
    links:
      - "mongo"


  harvester:
    image: "reflectoring/harvester:latest"
    restart: always
    ports:
      - "9090:9090"
    networks:
      - "backend"
    links:
      - "mongo"

networks:
  backend:

volumes:
  db-data:
