mongo:
  image: "mongo:3.2"

quartermaster:
  image: "reflectoring/quartermaster:latest"
  ports:
    - "8080:8080"
    - "8090:8090"
  links:
    - mongo:mongo

harvester:
  image: "reflectoring/harvester:latest"
  ports:
    - "9090:9090"
  links:
    - mongo:mongo
